In [6]:
import requests
import pandas as pd
from io import StringIO

header = {"User-Agent": "Mozilla/5.0"}

# WEB SCRAPE 1
url_worldometer = "https://www.worldometers.info/world-population/population-by-country/"

req_worldometer = requests.get(
    url_worldometer, headers=header, timeout=30
)
req_worldometer.raise_for_status()

html = req_worldometer.content.decode("utf-8")

tabel_worldometer = pd.read_html(StringIO(html))
df_populasi = tabel_worldometer[0]

print("Data Scraping Worldometer")
display(df_populasi.head())

Data Scraping Worldometer

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,1476625576,0.87%,12760051,497,2973190,"−440,456",1.93,29.2,37.6%,17.8%
1,2,China,1412914089,−0.22%,"−3,182,005",150,9388211,"−232,107",1.03,40.6,68.7%,17%
2,3,United States,349035494,0.51%,1759687,38,9147420,1177848,1.63,38.7,83.1%,4.2%
3,4,Indonesia,287886782,0.76%,2165546,159,1811570,"−39,472",2.08,30.7,60.3%,3.5%
4,5,Pakistan,259299791,1.6%,4080237,336,770880,"−1,144,738",3.44,20.8,34.7%,3.1%

In [7]:
# WEB SCRAPE 2
url_scrape = "https://www.scrapethissite.com/pages/forms/"
req_scrape = requests.get(url_scrape, headers=header)

tabel_scrape = pd.read_html(StringIO(req_scrape.text))

df_hoki = tabel_scrape[0]

print("Data Scraping ScrapThisSite:")
display(df_hoki.head())

Data Scraping ScrapThisSite:

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,NaN,0.550,299,264,35
1,Buffalo Sabres,1990,31,30,NaN,0.388,292,278,14
2,Calgary Flames,1990,46,26,NaN,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,NaN,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,NaN,0.425,273,298,-25